[theme]
primaryColor = "#0056b3"       # EUI Blue
backgroundColor = "#FAFAFA"    # Clean White/Grey
secondaryBackgroundColor = "#F0F2F6" 
textColor = "#333333"
font = "sans serif"

[server]
headless = true
port = 8501